export const AdvertInitialValues = {
	_id: '',
	tittle: '',
	price: {
		value: '',
		isNegotiable: ''
	},
	description: '',
	noOfviews: '',
	advertiser: {
		name: '',
		phoneNumber: '',
		_id: ''
	},
	address: {
		city: '',
		postcode: '',
		state: '',
		county: '',
		lat: '',
		lon: ''
	},
	images: [],
	mainCategory: '',
	subCategory: '',
	subSubCategory: '',
	createdAt: '',
	updatedAt: '',
	endAt: '',
	details: {
		brand: '',
		model: '',
		vinNumber: '',
		engineSize: '',
		productionYear: '',
		enginePower: '',
		fuel: '',
		bodyType: '',
		mileage: '',
		color: '',
		condition: '',
		techCondition: '',
		transmission: '',
		driveType: '',
		level: '',
		isFurnished: '',
		buildingType: '',
		livingArea: '',
		plotArea: '',
		numberOfRooms: '',
		numberOfFloors: '',
		typeOfPlot: '',
		rent: { value: '' },
		size: ''
	}
};

// export const AdvertInitialValues = {
// 	tittle: '',
// 	price: { value: '', currency: '', isNegotiable: '' },
// 	description: '',
// 	advertiser: { name: '', phoneNumber: '', _id: '' },
// 	address: { city: '', state: '', postcode: '', county: '' },
// 	images: [],
// 	mainCategory: '',
// 	subCategory: '',
// 	subSubCategory: '',
// 	details: {
// 		brand: '',
// 		model: '',
// 		vinNumber: '',
// 		engineSize: '',
// 		productionYear: '',
// 		enginePower: '',
// 		fuel: '',
// 		bodyType: undefined,
// 		mileage: '',
// 		color: '',
// 		techCondition: '',
// 		condition: '',
// 		transmission: undefined,
// 		driveType: undefined,
// 		level: undefined,
// 		isFurnished: '',
// 		buildingType: undefined,
// 		livingArea: '',
// 		plotArea: '',
// 		numberOfRooms: undefined,
// 		numberOfFloors: undefined,
// 		rent: { value: '' },
// 		typeOfPlot: '',
// 		size: '',
// 	},
// 	createdAt: '',
// 	updatedAt: '',
// 	endAt: ''
// }
